# Site settings
title: Suluh Sulistiawan
description: >- # this means to ignore newlines until "baseurl:"
  All knowledge is easy to learn, but difficult to understand.
  Like understanding a lover who is sometimes unclear what she wants!
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://suluh.my.id" # the base hostname & protocol for your site, e.g. http://example.com
repository: sProDev/suluh.my.id


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name          : Suluh Sulistiawan
  image         : /assets/img/avatar.jpg
  bio: All knowledge is easy to learn, but difficult to understand. Like understanding a lover who is sometimes unclear what she wants!
# behance       : your_username
# dribbble      : your_username
  email         : suluh.webdevelopers@hotmail.com
  facebook      : suluh.sulistiawan
  github        : sProDev
  gitlab        : SLuh
  instagram     : suluh_s
  linkedin      : suluh-sulistiawan
# medium        : your_username
# soundcloud    : your_username
# spotify       : your_username
# stackoverflow : your_user_id
  tumblr        : imgaguna.tumblr.com
# twitch        : your_username
  twitter       : suluh_s
  telegram      : suluh_s
# vimeo         : your_username
  youtube       : c/SDeveloper

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
