### Site Settings ###
title: Suluh Sulistiawan
description: >-
  All knowledge is easy to learn, but difficult to understand.
  Like understanding a lover who is sometimes unclear what she wants!
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
# repository: sProDev/suluh.my.id # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)

### Plugins ###
plugins:
  - jemoji
  - jekyll-minifier

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name: Suluh Sulistiawan
  nick: Suluh
  image: https://github.com/sProDev.png
  #behance: your_username
  #dribbble: your_username
  email: suluh.webdevelopers@hotmail.com
  facebook: suluh.sulistiawan
  github: sProDev
  gitlab: SLuh
  instagram: suluh_s
  #kaggle: your_username
  linkedin: suluh-sulistiawan
  #medium: your_username
  #soundcloud: your_username
  #spotify: your_username
  #stackoverflow: your_user_id
  tumblr: katamasker.tumblr.com
  #twitch: your_username
  twitter: suluh_s
  #vimeo: your_username
  telegram: suluh_s
  youtube: SDeveloper
  #keybase: your_username

### Posts ###
permalink: /read/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /project/:name

### Disqus ###
disqus:
  shortname: suluh # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true # Set to true to enable disqus comments

### Jekyll Minifier ###
jekyll-minifier:
  preserve_php: true
  remove_intertag_spaces: true
  compress_javascript: true

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
